inquisidores.varneshi = {
    datosValor: {
        nombre: "Varneshi",
        claseNivel: "Bardo 3",
        jugador: "Dani",
        raza: "Semi-Elfo",
        alineamiento: "Caótico Bueno",
        puntosExperiencia: "∞",
        fuerza: 9,
        destreza: 16,
        constitucion: 12,
        inteligencia: 10,
        sabiduria: 14,
        carisma: 19,
        bonificadorCompetencia: 2,
        salvacionFuerzaMod: -1,
        salvacionDestrezaMod: 5,
        salvacionConstitucionMod: 1,
        salvacionInteligenciaMod: 0,
        salvacionSabiduriaMod: 2,
        salvacionCarismaMod: 6,
        acrobacias: 5,
        atletismo: 1,
        conocimientoArcano: 0,
        enganyo: 6,
        historia: 0,
        interpretacion: 6,
        intimidacion: 4,
        investigacion: 0,
        juegoManos: 3,
        medicina: 2,
        naturaleza: 0,
        percepcion: 6,
        perspicacia: 4,
        persuasion: 6,
        religion: 0,
        sigilo: 7,
        supervivencia: 2,
        tratoAnimales: 2,
        percepcionPasiva: 12,
        otrasCompetenciasEIdiomas: "Lengua Común\n\
Armaduras Ligeras\n\
Armas sencillas y ballestas de mano\n\
Flauta, tambor y laúd",
        claseArmadura: 16,
        iniciativa: 3,
        velocidad: 30,
        puntosGolpeMaximos: 21,
        puntosGolpeActuales: 21,
        puntosGolpeTemporales: 0,
        totalDadosGolpe: "3d8",
        totalDadosRestantes: 3,
        piezasCobre: 1,
        piezasPlata: 1,
        piezasE: 1,
        piezasOro: 1,
        piezasPlatino: 1,
    }, datosCheck: {
        salvacionFuerzaCompetencia: false,
        salvacionDestrezaCompetencia: true,
        salvacionConstitucionCompetencia: false,
        salvacionInteligenciaCompetencia: false,
        salvacionSabiduriaCompetencia: false,
        salvacionCarismaCompetencia: true,
        acrobaciasCompetencia: true,
        atletismoCompetencia: true,
        conocimientoArcanoCompetencia: false,
        enganyoCompetencia: true,
        historiaCompetencia: false,
        interpretacionCompetencia: true,
        intimidacionCompetencia: false,
        investigacionCompetencia: false,
        juegoManosCompetencia: false,
        medicinaCompetencia: false,
        naturalezaCompetencia: false,
        percepcionCompetencia: true,
        perspicaciaCompetencia: true,
        persuasionCompetencia: true,
        religionCompetencia: false,
        sigiloCompetencia: true,
        supervivenciaCompetencia: false,
        tratoAnimalesCompetencia: false
    }
};